//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanchaypatraApp.UI
{


    public partial class Login
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SanchaypatraApp.Site Master
        {
            get
            {
                return ((SanchaypatraApp.Site)(base.Master));
            }
        }
    }
}
